apiVersion: v1
kind: Pod
metadata:
  name: podtest1
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
  labels:
    app: back
    env: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
  labels:
    app: back
    env: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
