apiVersion: v1
kind: Pod
metadata:
  name: podtest1
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
