apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Test Service Account"
  name: test
  labels:
    app: sa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-test
  template:
    metadata:
      labels:
        app: sa-test
    spec:
      containers:
      - name: nginx
        image: nginx
      serviceAccountName: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: sa-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: service-account # "name" is case sensitive
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: sa-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
