apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
   name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: dev
  name: cpu-min-max-demo-lr
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      cpu: 0.5
      memory: 100Mi
    type: Container
