apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
   name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: prod
  name: min-max-demo
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 1
    min:
      cpu: 0.1
      memory: 100Mi
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  namespace: prod
  name: nginxpod
spec:
  containers:
  - name: nginxtest
    image: nginx:alpine
    resources:
      limits:
        memory: 400Mi
        cpu: 0.5
      requests:
        memory: 100Mi
        cpu: 0.1
