apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
   name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "Create Deployment Dev"
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 110
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  annotations:
    kubernetes.io/change-cause: "Create Deployment Prod"
  name: deployment-test
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 110
