---
apiVersion: v1
kind: Pod
metadata:
  name: test-ram
spec:
  containers:
  - name: app
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes","250M", "--vm-hang", "1"]
