---
apiVersion: v1
kind: Pod
metadata:
  name: test-cpu
spec:
  containers:
  - name: app
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
      - -cpus
      - "2"
